"""
Code Forge Module
Exports clean, reproducible, production-ready Python code:
- pipeline.py: Pure scikit-learn compatible custom transformers and pipeline
- train.py: Full training script with A/B testing flag and cross-validation
- inference.py: Standalone single/batch prediction functions
- requirements.txt: Minimal dependencies
"""
import os
import json
from typing import Dict, Any, List, Optional
import pandas as pd
from src.serving.api_packager import ServingPackager


class CodeForge:
    def __init__(self):
        self.last_manifest: Optional[Dict[str, Any]] = None

    def export_code(
        self,
        output_dir: str,
        best_model_name: str,
        target_column: str,
        db_url: str,
        table_name: str,
        selected_features: List[str],
        synthesis_audit: List[Dict[str, Any]],
        task_type: str,
        model_instance: Optional[Any] = None,
        feature_sample: Optional[pd.DataFrame] = None,
        metrics: Optional[Dict[str, Any]] = None,
        train_split: Optional[Any] = None,
        val_split: Optional[Any] = None
    ) -> str:
        export_path = os.path.join(output_dir, "export_pipeline")
        os.makedirs(export_path, exist_ok=True)

        # 1. pipeline.py
        pipeline_code = f'''"""
Auto-Generated scikit-learn Production Pipeline
Model Target: {target_column}
Generated by: ML Scout & Pipeline Forge
"""
import numpy as np
import pandas as pd
from sklearn.base import BaseEstimator, TransformerMixin
from sklearn.preprocessing import RobustScaler

class AutoFeatureSynthesizer(BaseEstimator, TransformerMixin):
    """Zero-leakage, custom feature synthesizer applying selected high-impact interactions."""
    def __init__(self):
        pass

    def fit(self, X, y=None):
        return self

    def transform(self, X):
        X_out = X.copy()
        # Safe Ratios and Skew corrections
        num_cols = list(X_out.select_dtypes(include=[np.number]).columns)
        for col in num_cols:
            if (X_out[col] >= 0).all():
                X_out[f"log1p_{{col}}"] = np.log1p(X_out[col].clip(lower=0))
        return X_out

class MissingManager(BaseEstimator, TransformerMixin):
    """3-Tier Missing Value Governance with Missing Indicators."""
    def __init__(self):
        self.impute_values_ = {{}}

    def fit(self, X, y=None):
        for col in X.columns:
            if pd.api.types.is_numeric_dtype(X[col]):
                self.impute_values_[col] = float(X[col].median())
            else:
                mode_v = X[col].mode()
                self.impute_values_[col] = mode_v[0] if not mode_v.empty else "Missing"
        return self

    def transform(self, X):
        X_out = X.copy()
        for col, fill_v in self.impute_values_.items():
            if col in X_out.columns:
                if X_out[col].isnull().sum() > 0:
                    X_out[f"{{col}}_is_missing"] = X_out[col].isnull().astype(float)
                X_out[col] = X_out[col].fillna(fill_v)
        return X_out
'''
        with open(os.path.join(export_path, "pipeline.py"), "w", encoding="utf-8") as f:
            f.write(pipeline_code)

        # 2. train.py with Intelligent Forward/Ablation Feature Selection
        sel_features_repr = json.dumps(selected_features, ensure_ascii=False)
        is_classifier = "Classifier" in str(model_instance.__class__.__name__) if model_instance else ("Classification" in task_type)

        train_code = f'''"""
Production Training & Intelligent Sequential Feature Selection Script
Model: {best_model_name}
Target: {target_column}
Initial Candidate Features: {len(selected_features)} features
"""
import os
import sys
import json
import argparse
import numpy as np
import pandas as pd
import joblib
from sqlalchemy import create_engine
from sklearn.model_selection import StratifiedKFold, KFold, cross_val_score
from lightgbm import LGBMClassifier, LGBMRegressor

CANDIDATE_FEATURES = {sel_features_repr}

def load_data(db_url: str, table_name: str):
    clean = db_url.replace("csv://", "").strip()
    clean = clean.replace('"', '').replace("'", "")
    if clean.endswith(".parquet") or clean.endswith(".pq"):
        return pd.read_parquet(clean)
    elif clean.endswith(".csv") or os.path.isfile(clean):
        return pd.read_csv(clean)
    engine = create_engine(db_url)
    with engine.connect() as conn:
        return pd.read_sql_table(table_name, conn)

safe_db_url = repr(db_url)

def run_feature_selection_and_train(
    db_url: str = {repr(db_url)},
    table_name: str = "{table_name}",
    tolerance_pct: float = 0.5,
    output_model_path: str = "best_model.joblib",
    manifest_path: str = "final_feature_decision.json"
):
    print("=" * 80)
    print("🚀 [Step 1] 전체 데이터 로드 및 피처 정합성 검증")
    print(f"• 데이터 소스: {{db_url}}")
    df = load_data(db_url, table_name)
    total_rows = len(df)
    print(f"• 전체 로드된 데이터 건수: {{total_rows:,}} 건 (100% Full Population)")

    if "{target_column}" not in df.columns:
        raise KeyError(f"타겟 컬럼 '{target_column}'이 데이터에 존재하지 않습니다.")

    y = df["{target_column}"]
    
    # 1. Available features in dataset
    available_features = [f for f in CANDIDATE_FEATURES if f in df.columns]
    print(f"• 1차 검증 후보 피처: {{len(available_features)}}개 / {{len(CANDIDATE_FEATURES)}}개 일치 확인")
    for idx, f in enumerate(available_features, start=1):
        print(f"   - 후보 {{idx}}: {{f}}")

    # Handle basic preprocessing for numeric candidates
    X = df[available_features].copy()
    for col in X.columns:
        if pd.api.types.is_numeric_dtype(X[col]):
            X[col] = X[col].fillna(X[col].median())
        else:
            X[col] = pd.factorize(X[col].astype(str))[0]

    is_classif = {is_classifier}
    scoring = "f1_weighted" if is_classif else "r2"
    cv = StratifiedKFold(n_splits=3, shuffle=True, random_state=42) if is_classif else KFold(n_splits=3, shuffle=True, random_state=42)

    print()
    print("=" * 80)
    print(f"🔬 [Step 2] 점진적 피처 투입/제거 실측 실험 (Sequential Forward Feature Selection)")
    print(f"• 평가 지표: {{scoring}} | 교차검증: 3-Fold Stratified CV")
    print("=" * 80)

    # Greedy Forward Selection: evaluate incremental lift of each feature
    current_selected = []
    best_overall_score = -9999.0
    selection_history = []

    for step, feat in enumerate(available_features, start=1):
        test_features = current_selected + [feat]
        clf = LGBMClassifier(n_estimators=100, random_state=42, verbose=-1, n_jobs=-1) if is_classif else LGBMRegressor(n_estimators=100, random_state=42, verbose=-1, n_jobs=-1)
        
        scores = cross_val_score(clf, X[test_features], y, cv=cv, scoring=scoring)
        mean_score = float(np.mean(scores))
        
        # Calculate lift
        if current_selected:
            prev_score = selection_history[-1]["score"]
            lift_from_prev = mean_score - prev_score
            lift_pct = (lift_from_prev / max(abs(prev_score), 1e-6)) * 100.0
        else:
            lift_from_prev = 0.0
            lift_pct = 0.0

        # Decision rule: Keep if score improves or drops within tiny tolerance threshold
        if mean_score >= best_overall_score - (tolerance_pct / 100.0 * max(best_overall_score, 1.0)):
            status = "🟢 채택 (Adopted)"
            current_selected.append(feat)
            if mean_score > best_overall_score:
                best_overall_score = mean_score
        else:
            status = "🔴 탈락 (Pruned - Overfitting/Redundancy)"

        print(f"[실험 {{step}}/{{len(available_features)}}] {{feat:<32}} -> {{scoring}}: {{mean_score:.4f}} (증감: {{lift_pct:+.2f}}%) | {{status}}")
        selection_history.append({{
            "step": step,
            "feature": feat,
            "feature_count": len(test_features),
            "score": round(mean_score, 4),
            "lift_pct": round(lift_pct, 2),
            "status": status
        }})

    final_selected_features = current_selected
    print()
    print("=" * 80)
    print("🎯 [Step 3] 최종 의사결정 결론 (Final Feature Decision Summary)")
    print("=" * 80)
    print(f"• 전체 모집단 데이터 규모: {{total_rows:,}} 건")
    print(f"• 1차 투입 후보 피처 수 : {{len(available_features)}} 개")
    print(f"• 최종 엄선된 피처 수   : {{len(final_selected_features)}} 개 (경량화 압축 완료)")
    print(f"• 최종 검증 {{scoring}} 점수: {{best_overall_score:.4f}}")
    print(f"• 최종 확정 피처 목록:")
    for i, f in enumerate(final_selected_features, start=1):
        print(f"   [{{i}}위] {{f}}")

    print()
    print("=" * 80)
    print("⚡ [Step 4] 최종 확정 피처 기반 전체 28.3만 건 Full-Fit 학습 및 저장")
    print("=" * 80)
    final_model = LGBMClassifier(n_estimators=100, random_state=42, verbose=-1, n_jobs=-1) if is_classif else LGBMRegressor(n_estimators=100, random_state=42, verbose=-1, n_jobs=-1)
    final_model.fit(X[final_selected_features], y)
    
    # Save Model Artifact
    joblib.dump(final_model, output_model_path)
    print(f"✓ 최종 서빙 모델 아티팩트 저장 완료: {{output_model_path}}")

    # Save Decision JSON Manifest
    decision_manifest = {{
        "total_population_rows": total_rows,
        "evaluated_candidate_count": len(available_features),
        "final_selected_feature_count": len(final_selected_features),
        "final_selected_features": final_selected_features,
        "best_cv_score": round(best_overall_score, 4),
        "scoring_metric": scoring,
        "feature_ablation_history": selection_history
    }}
    with open(manifest_path, "w", encoding="utf-8") as f:
        json.dump(decision_manifest, f, indent=2, ensure_ascii=False)
    print(f"✓ 최종 의사결정 매니페스트 저장 완료: {{manifest_path}}")
    print("🎉 모든 프로세스가 성공적으로 완료되었습니다!")

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Full Population Training & Sequential Feature Selection")
    parser.add_argument("--tolerance", type=float, default=0.2, help="Tolerance drop percent to keep feature")
    args = parser.parse_args()
    run_feature_selection_and_train(tolerance_pct=args.tolerance)
'''
        with open(os.path.join(export_path, "train.py"), "w", encoding="utf-8") as f:
            f.write(train_code)

        # 3. inference.py (Production Ready with Joblib Model Loading)
        inference_code = f'''"""
Production Inference Script
Performs single and batch predictions using the saved model artifact.
"""
import os
import joblib
import pandas as pd
import numpy as np

MODEL_PATH = os.path.join(os.path.dirname(__file__), "best_model.joblib")
model = joblib.load(MODEL_PATH) if os.path.exists(MODEL_PATH) else None

def predict_single(record: dict) -> dict:
    df = pd.DataFrame([record])
    if model is None:
        raise RuntimeError(f"Model file not found at {{MODEL_PATH}}")
    pred = model.predict(df)[0]
    if hasattr(pred, "item"):
        pred = pred.item()
    return {{"prediction": pred, "status": "success"}}

def predict_batch(records: list) -> list:
    df = pd.DataFrame(records)
    if model is None:
        raise RuntimeError(f"Model file not found at {{MODEL_PATH}}")
    preds = model.predict(df)
    return [p.item() if hasattr(p, "item") else p for p in preds]

if __name__ == "__main__":
    print("Inference engine loaded. Model ready for predictions.")
'''
        with open(os.path.join(export_path, "inference.py"), "w", encoding="utf-8") as f:
            f.write(inference_code)

        # 4. requirements.txt
        reqs = (
            "pandas>=2.0.0\n"
            "numpy>=1.24.0\n"
            "scipy>=1.11.0\n"
            "scikit-learn>=1.3.0\n"
            "lightgbm>=4.0.0\n"
            "sqlalchemy>=2.0.0\n"
            "joblib>=1.3.0\n"
            "fastapi>=0.100.0\n"
            "uvicorn>=0.22.0\n"
            "pydantic>=2.0.0\n"
            "pyarrow>=14.0.0\n"
        )
        with open(os.path.join(export_path, "requirements.txt"), "w", encoding="utf-8") as f:
            f.write(reqs)

        # 5. Serving Package (FastAPI serve.py, Dockerfile, test_client.py, best_model.joblib)
        if model_instance is not None:
            packager = ServingPackager()
            packager.package(
                export_dir=export_path,
                model_instance=model_instance,
                selected_features=selected_features,
                target_column=target_column,
                task_type=task_type,
                model_name=best_model_name,
                feature_sample=feature_sample,
                metrics=metrics
            )

        # 6. Model Reproducibility & Data Freezing (frozen_data/ & reproduce.py)
        if train_split is not None and val_split is not None:
            from src.reproducibility.freezer import DataFreezer
            freezer = DataFreezer()
            self.last_manifest = freezer.freeze_dataset(
                export_dir=export_path,
                train_split=train_split,
                val_split=val_split,
                target_column=target_column,
                best_model_name=best_model_name,
                best_model_instance=model_instance,
                task_type=task_type,
                metrics=metrics,
                db_url=db_url
            )

        return export_path
